scrape_configs:
  - job_name: 'taxi-provider'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'driver-service'
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'passenger-service'
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'ride-service'
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'rating-service'